version: "3.0"

services:
  gateway:
    build:
      context: .
    image: conduit
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    links:
      - nats
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

    #deploy:
    #  replicas: 2

  articles:
    build:
      context: .
    image: conduit
    env_file: docker-compose.env
    environment:
      SERVICES: articles
    links:
      - nats
      - mongo
    depends_on:
      - nats
      - mongo
    #deploy:
    #  replicas: 2

  comments:
    build:
      context: .
    image: conduit
    env_file: docker-compose.env
    environment:
      SERVICES: comments
    links:
      - nats
      - mongo
    depends_on:
      - nats
      - mongo
    #deploy:
    #  replicas: 2

  favorites:
    build:
      context: .
    image: conduit
    env_file: docker-compose.env
    environment:
      SERVICES: favorites
    links:
      - nats
      - mongo
    depends_on:
      - nats
      - mongo
    #deploy:
    #  replicas: 2

  follows:
    build:
      context: .
    image: conduit
    env_file: docker-compose.env
    environment:
      SERVICES: follows
    links:
      - nats
      - mongo
    depends_on:
      - nats
      - mongo
    #deploy:
    #  replicas: 2

  users:
    build:
      context: .
    image: conduit
    env_file: docker-compose.env
    environment:
      SERVICES: users
    links:
      - nats
      - mongo
    depends_on:
      - nats
      - mongo
    #deploy:
    #  replicas: 2

  nats:
    image: nats
    ports:
      - "4222:4222"

  mongo:
    image: mongo
    volumes:
      - ./db:/data/db

  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "3000:80"
      - "3001:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - /dev/null:/traefik.toml
